# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MueT5kEbdiX9BVNkLkll5rNo2kwJr1As
"""

# ============================================
# PART 2 — Pandas Exploration
# Google Colab Python Code
# ============================================

# Step 1: Import Libraries
import pandas as pd
import numpy as np

# Step 2: Upload Dataset in Google Colab
from google.colab import files
uploaded = files.upload()

# Step 3: Load Dataset using Pandas
# Get the name of the first uploaded file
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# ============================================
# 1. Display Dataset
# ============================================

print("Complete Dataset:\n")
print(df)

# ============================================
# 2. Display First 5 Rows
# ============================================

print("\nFirst 5 Rows:\n")
print(df.head())

# ============================================
# 3. Check Data Types of All Columns
# ============================================

print("\nData Types of Columns:\n")
print(df.dtypes)

# ============================================
# 4. Find Total Missing Values in Each Column
# ============================================

print("\nMissing Values in Each Column:\n")
print(df.isnull().sum())

# ============================================
# 5. Find Students with Attendance Below 70%
# ============================================

low_attendance = df[df['attendance'] < 70]

print("\nStudents with Attendance Below 70%:\n")
print(low_attendance)

# ============================================
# Optional: Display Selected Columns Only
# ============================================

print("\nNames and Attendance of Students Below 70%:\n")
print(low_attendance[['name', 'attendance']])