# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MueT5kEbdiX9BVNkLkll5rNo2kwJr1As
"""

# ============================================
# PART 4 — Data Analysis
# Google Colab Python Code
# ============================================

# Step 1: Import Libraries
import pandas as pd
import numpy as np

# Step 2: Upload Dataset
from google.colab import files
uploaded = files.upload()

# Step 3: Load Dataset
# Get the name of the first uploaded file
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# ============================================
# Basic Data Cleaning
# ============================================

# Fill missing numerical values with mean

numerical_cols = ['math_score', 'science_score', 'attendance']

for col in numerical_cols:
    if col in df.columns: # Added check for column existence
        df[col] = df[col].fillna(df[col].mean()) # Modified to avoid FutureWarning

# Convert age column to numeric
if 'age' in df.columns: # Added check for column existence
    df['age'] = pd.to_numeric(df['age'], errors='coerce')

    # Fill missing age values
    df['age'] = df['age'].fillna(df['age'].mean()) # Modified to avoid FutureWarning

# ============================================
# 1. Create New Column average_score
# ============================================

# Ensure both 'math_score' and 'science_score' exist before calculating average
if 'math_score' in df.columns and 'science_score' in df.columns:
    df['average_score'] = (
        df['math_score'] + df['science_score']
    ) / 2

    print("Dataset with Average Score:\n")
    print(df[['name', 'math_score', 'science_score', 'average_score']])
else:
    print("Cannot calculate 'average_score' as 'math_score' or 'science_score' column is missing.")

# ============================================
# 2. Find Top 5 Students
# ============================================

if 'average_score' in df.columns: # Added check for column existence
    top_students = df.sort_values(
        by='average_score',
        ascending=False
    ).head(5)

    print("\nTop 5 Students Based on Average Score:\n")
    print(top_students[['name', 'average_score']])
else:
    print("Cannot find top students as 'average_score' column is missing.")

# ============================================
# 3. Correlation Between Attendance and Marks
# ============================================

if 'attendance' in df.columns and 'average_score' in df.columns: # Added check for column existence
    correlation = df[['attendance', 'average_score']].corr()

    print("\nCorrelation Matrix:\n")
    print(correlation)
else:
    print("Cannot calculate correlation as 'attendance' or 'average_score' column is missing.")

# ============================================
# Correlation Formula
# ============================================

print("\nCorrelation Formula:")
print("r = Σ(x - x̄)(y - ȳ) / √[Σ(x - x̄)^2 * Σ(y - ȳ)^2]")

# ============================================
# 4. Group Students by Gender
# and Calculate Average Marks
# ============================================

if 'gender' in df.columns and 'average_score' in df.columns: # Added check for column existence
    gender_group = df.groupby('gender')[
        'average_score'
    ].mean()

    print("\nAverage Marks Grouped by Gender:\n")
    print(gender_group)
else:
    print("Cannot group by gender as 'gender' or 'average_score' column is missing.")

# ============================================
# Final Dataset
# ============================================

print("\nFinal Dataset:\n")
print(df.head())