# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MueT5kEbdiX9BVNkLkll5rNo2kwJr1As
"""

# ============================================
# PART 3 — Data Preprocessing
# Google Colab Python Code
# ============================================

# Step 1: Import Libraries
import pandas as pd
import numpy as np

# Step 2: Upload Dataset
from google.colab import files
uploaded = files.upload()

# Step 3: Load Dataset
# Get the name of the first uploaded file
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# ============================================
# 1. Identify Missing Values
# ============================================

print("Missing Values Before Handling:\n")
print(df.isnull().sum())

# ============================================
# 2. Handle Missing Values
# ============================================

# Fill numerical columns with mean

numerical_cols = ['math_score', 'science_score', 'attendance']

for col in numerical_cols:
    # Check if column exists before trying to fillna
    if col in df.columns:
        df[col].fillna(df[col].mean(), inplace=True)

# Fill categorical columns with mode

categorical_cols = ['gender', 'exam_date', 'age']

for col in categorical_cols:
    # Check if column exists before trying to fillna
    if col in df.columns:
        df[col].fillna(df[col].mode()[0], inplace=True)

print("\nMissing Values After Handling:\n")
print(df.isnull().sum())

# ============================================
# 3. Convert Incorrect Data Formats
# ============================================

# Convert age column into numeric datatype
# Invalid values become NaN

if 'age' in df.columns:
    df['age'] = pd.to_numeric(df['age'], errors='coerce')

    # Replace NaN values with mean age

    df['age'].fillna(df['age'].mean(), inplace=True)

    print("\nAge Column After Conversion:\n")
    print(df['age'])
else:
    print("\n'age' column not found, skipping age conversion.")

# ============================================
# 4. Convert exam_date into Datetime Format
# ============================================

if 'exam_date' in df.columns:
    df['exam_date'] = pd.to_datetime(df['exam_date'], errors='coerce')

    print("\nExam Date Column:\n")
    print(df['exam_date'])
else:
    print("\n'exam_date' column not found, skipping exam_date conversion.")

# ============================================
# 5. Detect and Remove Outliers
# Using IQR Method
# ============================================

def remove_outliers(dataframe, column):

    Q1 = dataframe[column].quantile(0.25)
    Q3 = dataframe[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    filtered_df = dataframe[
        (dataframe[column] >= lower_bound) &
        (dataframe[column] <= upper_bound)
    ]

    return filtered_df

# Remove outliers from math_score
if 'math_score' in df.columns:
    df = remove_outliers(df, 'math_score')

# Remove outliers from science_score
if 'science_score' in df.columns:
    df = remove_outliers(df, 'science_score')

print("\nDataset After Removing Outliers:\n")
print(df)

# ============================================
# 6. Find Duplicate Rows
# ============================================

print("\nNumber of Duplicate Rows:")
print(df.duplicated().sum())

# ============================================
# 7. Remove Duplicate Rows
# ============================================

df = df.drop_duplicates()

print("\nDataset After Removing Duplicates:\n")
print(df)

# ============================================
# Final Cleaned Dataset
# ============================================

print("\nFinal Cleaned Dataset:\n")
print(df.head())