# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MueT5kEbdiX9BVNkLkll5rNo2kwJr1As
"""

# ============================================
# PART 1 — NumPy Operations
# Google Colab Python Code
# ============================================

# Step 1: Import Libraries
import numpy as np
import pandas as pd

# Step 2: Upload Dataset in Google Colab
from google.colab import files
uploaded = files.upload()

# Step 3: Load Dataset
df = pd.read_csv('student_scores.csv')

# Display Dataset
print("Dataset:\n")
print(df)

# ============================================
# 1. Create NumPy Array from math_score column
# ============================================

math_scores = np.array(df['math_score'])

print("\nNumPy Array of Math Scores:\n")
print(math_scores)

# ============================================
# 2. Find Mean, Median, Maximum, Minimum
# ============================================

# Using nan functions to ignore missing values

mean_value = np.nanmean(math_scores)
median_value = np.nanmedian(math_scores)
max_value = np.nanmax(math_scores)
min_value = np.nanmin(math_scores)

print("\nStatistical Values:\n")

print("Mean =", mean_value)
print("Median =", median_value)
print("Maximum =", max_value)
print("Minimum =", min_value)

# ============================================
# 3. Normalize the Scores
# ============================================

# Formula:
# (X - Xmin) / (Xmax - Xmin)

normalized_scores = (
    (math_scores - np.nanmin(math_scores))
    /
    (np.nanmax(math_scores) - np.nanmin(math_scores))
)

print("\nNormalized Math Scores:\n")
print(normalized_scores)